
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LAB-RPL2-PC07
 */
public class pendaftaransiswabaru extends javax.swing.JFrame {
    Connection koneksi;
    String id = "";
    /**
     * Creates new form pendaftaransiswabaru
     */
    public pendaftaransiswabaru() {
        initComponents();
        koneksi();
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        sekolahasal = new javax.swing.JTextField();
        agama = new javax.swing.JComboBox<>();
        laki = new javax.swing.JRadioButton();
        perempuan = new javax.swing.JRadioButton();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("PENDAFTARAN SISWA BARU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 13, -1, -1));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Alamat", "Jenis Kelamin", "Agama", "Sekolah Asal"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 268, 549, 112));

        jLabel2.setText("Nama                          :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 51, -1, -1));

        jLabel3.setText("Alamat                        :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 79, -1, -1));

        jLabel4.setText("Jenis Kelamin             :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 175, -1, -1));

        jLabel5.setText("Agama                        :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 199, -1, -1));

        jLabel6.setText("Sekolah Asal               :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 228, -1, -1));
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 48, 242, -1));

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane2.setViewportView(alamat);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 79, 242, -1));
        getContentPane().add(sekolahasal, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 228, 241, -1));

        agama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "islam", "kristen", "katholik", "hindu", "budha" }));
        getContentPane().add(agama, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 199, 242, -1));

        laki.setText("Laki-laki");
        getContentPane().add(laki, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 171, -1, -1));

        perempuan.setText("Perempuan");
        getContentPane().add(perempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 171, -1, -1));

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 80, -1));

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 80, -1));

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 45, 80, -1));

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        if (id == "") {
            create();
        } else {
            update();
        }      
    }//GEN-LAST:event_simpanActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        delete();        // TODO add your handling code here:
    }//GEN-LAST:event_hapusActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
edit();        // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
clear();        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pendaftaransiswabaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pendaftaransiswabaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pendaftaransiswabaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pendaftaransiswabaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pendaftaransiswabaru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> agama;
    private javax.swing.JTextArea alamat;
    private javax.swing.JButton clear;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton laki;
    private javax.swing.JTextField nama;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JTextField sekolahasal;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables

private void koneksi() {
    try {
        String server = "jdbc:mysql://localhost:3306/db_pendaftaransiswa";
        String user = "root";
        String pass = "";
        
        DriverManager.registerDriver(new com.mysql.cj.jdbc.Driver());
        koneksi = DriverManager.getConnection(server, user, pass);
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}

private void tampil() {
    DefaultTableModel data = (DefaultTableModel) tabel.getModel();
    data.setRowCount(0);
    
    try {
        String sql = "SELECT *FROM tb_siswa";
        ResultSet res = koneksi.createStatement().executeQuery(sql);
        
        while (res.next()) {
            data.addRow(new Object[] {
                res.getString(1), res.getString(2),
                res.getString(3), res.getString(4),
                res.getString(5), res.getString(6)
            });
            
        }
        tabel.setModel(data);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    }

private void create() {
    String jk = (laki.isSelected()) ? "laki-laki" : "perempuan";
        String sql = "INSERT INTO tb_siswa VALUES(null,"
                + "'" + nama.getText() + "',"
                + "'" + alamat.getText() + "',"
                + "'" + jk + "',"
                + "'" + agama.getSelectedItem().toString() + "',"
                + "'" + sekolahasal.getText() + "')";
        
    try {
        int res = koneksi.createStatement().executeUpdate(sql);
        if (res > -1) {
            tampil();
            nama.setText("");
            alamat.setText("");
            laki.setSelected(false);
            perempuan.setSelected(false);
            agama.setSelectedIndex(0);
            sekolahasal.setText("");
        }
    } catch (Exception e) {
    JOptionPane.showMessageDialog(null, e);
    }
}

private void delete() {
           int row = tabel.getSelectedRow();
           String id = tabel.getValueAt(row, 0).toString();
           
           try {
               String sql = "DELETE FROM tb_siswa WHERE id="+id;
               int res = koneksi.createStatement().executeUpdate(sql);
               
               if (res > -1) {
                   tampil();
               }
           } catch (Exception e) {
               JOptionPane.showMessageDialog(null, e);
           }
       }

private void edit() {
           int row = tabel.getSelectedRow();
           String id_siswa = tabel.getModel().getValueAt(row, 0).toString();
           
           try {
               String sql = "SELECT * FROM tb_siswa WHERE id="+id_siswa;
               ResultSet res = koneksi.createStatement().executeQuery(sql);
               
               while (res.next()) {
                  id = res.getString(1);
                  nama.setText(res.getString(2));
                  alamat.setText(res.getString(3));
                   if (res.getString(4).equals("laki-laki")) {
                       laki.setSelected(true);
                   } else {
                       perempuan.setSelected(true);
                   }
                   agama.setSelectedItem(res.getString(5));
                   sekolahasal.setText(res.getString(6));
                   edit.setEnabled(false);
               }
           } catch (Exception e) {
               JOptionPane.showMessageDialog(null, e);
           }
       }

private void clear() {
           id = null;
           nama.setText("");
           alamat.setText("");
           laki.setSelected(false);
           agama.setSelectedIndex(0);
           sekolahasal.setText("");
           edit.setEnabled(true);
       }

private void update() {
    String jk = (laki.isSelected()) ? "laki-laki" : "perempuan";
    String sql = "UPDATE tb_siswa SET "
                + "nama = '" + nama.getText() + "',"
                + "alamat = '" + alamat.getText() + "',"
                + "jk = '" + jk + "',"
                + "agama = '" + agama.getSelectedItem().toString() + "',"
                + "sekolahasal = '" + sekolahasal.getText() + "'"
                + "WHERE id = "+id;
    
    try {
        int res = koneksi.createStatement().executeUpdate(sql);
        if (res > -1) {
            tampil();
            clear();
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
               
}


}


